ALTER TABLE "Gallery" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Photo"   ADD COLUMN IF NOT EXISTS "lightboxViews" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Photo"   ADD COLUMN IF NOT EXISTS "downloadCount" INTEGER NOT NULL DEFAULT 0;
