ALTER TABLE "Gallery" ADD COLUMN IF NOT EXISTS "desktopViews" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Gallery" ADD COLUMN IF NOT EXISTS "tabletViews"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Gallery" ADD COLUMN IF NOT EXISTS "mobileViews"  INTEGER NOT NULL DEFAULT 0;
